# Load in NumPy (remember to pip install numpy first)

In [1]:
! pip install numpy


[notice] A new release of pip is available: 24.0 -> 24.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip


# Why is NumPy Faster? - Fixed Type , Contiguous memory
# 1. Faster to read less bytes of memory
# 2. Faster to perform operations on the same type of data



In [2]:
import numpy as np

In [5]:
a = np.array([1,3,4])
b = np.array([2,2,2])
print(a*b)

[2 6 8]


# Application of NumPy?
# 1. Mathematics(MATLAB Replacement)
# 2. Plotting(Matplotlib)
# 3. Backend
# 4. Machine Learning

# The Basics

In [20]:
a = np.array([1,2,3], dtype='int32')
print(a)

[1 2 3]


In [7]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


# Get Dimension

In [10]:
a.ndim # number of dimension
b.ndim


2

# Get Shape

In [104]:
print(b.shape)

(3, 2)


In [18]:
# Get Type
a.dtype

dtype('int16')

In [21]:
# Get Size
a.itemsize

4

In [23]:
# Get total size
a.size * a.itemsize # We can use = a.nbytes # number of bytes

12

# Accessing/Changing specific elements, rows, columns, etc

In [26]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [27]:
# Get a specifc element [row,coloumn]
a[1,5]


13

In [110]:
# Get a specific row
a[0:,]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
# Get a specific column
a[:,2]

array([ 3, 10])

In [30]:
# Getting a little more fancy[startindex:endindex:stepsize]
a[0,1:6:2]


array([2, 4, 6])

In [32]:
a[1,5]=20
print(a)

a [:,2]=5
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]
[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 20 14]]


# *3-d example

In [34]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [36]:
# Get specific element (work outside in)
b[0,1,1]
b[:,1,:]

array([[3, 4],
       [7, 8]])

In [39]:
# replace 
b[:,1,:] = [[9,9],[8,8]]
print(b)

[[[1 2]
  [9 9]]

 [[5 6]
  [8 8]]]


# Initializing Different Types of Arrays

In [45]:
# All 0s matrix
np.zeros((2,3,3,2))


array([[[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]]])

In [46]:
# All 1s matrix
np.ones((4,2,2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [47]:
# Any other number
np.full((2,2),22)

array([[22, 22],
       [22, 22]])

In [48]:
# Any other number(ful_like)
np.full_like(a,4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [50]:
# Random decimal numbers
np.random.rand(4,2,3)

array([[[5.27528364e-01, 1.56913820e-01, 3.37333510e-04],
        [1.50190573e-01, 3.54828544e-01, 5.96864376e-01]],

       [[7.79987010e-01, 4.36113118e-01, 5.79042833e-01],
        [8.23421812e-01, 8.23015569e-01, 1.04691480e-01]],

       [[2.40651746e-01, 9.49120327e-01, 3.91050027e-01],
        [5.59709657e-01, 5.19671794e-02, 3.25618603e-01]],

       [[7.45865521e-01, 9.57503600e-01, 9.54488431e-01],
        [5.97618743e-01, 8.62866812e-01, 2.55686442e-02]]])

In [54]:
# Random Integer Values
np.random.randint(-4,7,size=(3,3))

array([[-2,  6, -4],
       [ 5, -1,  6],
       [ 4,  4, -1]])

In [55]:
# The identity matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [58]:
arr= np.array([1,2,3])
arr1 = np.repeat(arr,3, axis=0)
print(arr1)

[1 1 1 2 2 2 3 3 3]


In [61]:
output = np.ones((5,5))
print(output)

z= np.zeros((3,3))
print(z)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [62]:
z[1,1]=9
print(z)

[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]


In [63]:
output[1:4 , 1:4] =z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [65]:
a = np.array([1,2,3,4])
print(a)
b=a
b[0]=100
print(a)

[1 2 3 4]
[100   2   3   4]


# Mathematics

In [66]:
a = np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [69]:
print(a+2)

[3 4 5 6 7]


In [70]:
print(a-2)

[-1  0  1  2  3]


In [71]:
print(a*2)

[ 2  4  6  8 10]


In [72]:
print(a/2)

[0.5 1.  1.5 2.  2.5]


In [76]:
b = np.array([1,0,1,0,1])
print(a + b)

[2 2 4 4 6]


In [78]:
print(a **2)

[ 1  4  9 16 25]


In [80]:
# Take the sin
print(np.cos(a))

[ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219]


# Linear Algebra

In [82]:
a = np.ones((2,3))
print(a)
b= np.full((3,2),2)
print(b)

print(np.matmul(a,b)) # matrix multiply

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]
[[6. 6.]
 [6. 6.]]


In [83]:
# Find the determinant
c=np.identity(3)
np.linalg.det(c)

1.0

# Statistics

In [84]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [85]:
np.min(stats)

1

In [88]:
print(np.max(stats, axis=1))

[3 6]


In [89]:
print(np.sum(stats,axis=0))

[5 7 9]


# Reorganizing Arrays

In [91]:
before= np.array([[1,2,3,4],[5,6,7,8]])
print(before)
print(before.shape)

[[1 2 3 4]
 [5 6 7 8]]
(2, 4)


In [97]:
after = before.reshape((4,2))
print(after)
after = before.reshape((2,2,2))
print(after)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [98]:
# Verticallt stacking vectors
v1= np.array([1,2,3,4])
v2= np.array([5,6,7,8])
np.vstack([v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [100]:
# Horizontal stack
h1 = np.ones((2,4))
h2=np.zeros((2,2))
h1
h2
np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

# delimiter used as ","

# Miscellaneous

In [102]:
# Load Data from file

In [ ]:
# filedata = np.getfromtxt("data.txt", delimiter = ",")
# filedata = filedata.astype("int32")
# print(filedata)

# Boolean Masking and Advanced Indexing

In [103]:
# filedata[filedata>50]

# You can index with a list in Numpy
a = np.array([1,2,3,4,5,6,7,8,9])
a[[1,2,8]]

array([2, 3, 9])