In [1]:
! pip install numpy


[notice] A new release of pip is available: 24.0 -> 24.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
import numpy as np

In [3]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [ ]:
import numpy as np
arr = np.array(42) # zero dimension
print(arr)

42


In [6]:
import numpy as np
arr = np.array([[1,2,3],[4,5,6]])
print(arr.reshape(-1))

[1 2 3 4 5 6]


In [7]:
# iterate through the arrays
arr = np.array([1,2,3,4,5])
for x in arr:
    print(x)

1
2
3
4
5


In [8]:
a = np.array([[[1,2],[3,4]],[[4,5],[6,7]]])
for x in np.nditer(a):
    print(x)

1
2
3
4
4
5
6
7


In [9]:
# join two arrays
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
arr3 = np.concatenate((arr1,arr2), axis=0)
print(arr3)

[1 2 3 4 5 6]


In [10]:
# searching and Sorting array

# Searching array
a = np.array([1,2,3])
a1 = np.where(a==3)
print(a1)

(array([2], dtype=int64),)


In [11]:
# sorting array
a = np.array([1,23,12,55,113,20])
print(np.sort(a))

[  1  12  20  23  55 113]


In [13]:
from numpy import random

In [14]:
x = random.uniform(2,3)
print(x)

2.9517394351292983


In [20]:
# Choice 
from numpy import random

x = random.choice([3,5,7,9])
print(x)

5


In [21]:
import numpy as np
arr = np.arange(1,10)
print(np.log2(arr))

[0.         1.         1.5849625  2.         2.32192809 2.5849625
 2.80735492 3.         3.169925  ]


In [22]:
# LCM and HCF
num1 = 2
num2 = 4
x = np.lcm(num1, num2)
print(x)

4


In [24]:
a = np.array([1,2,3,4,5])
x = np.lcm.reduce(a)
print(x)

60
